export const specialButtons = [
    { label: "+ gà", type: "+gà" },
    { label: "- gà", type: "-gà" },
    { label: "Tứ Quý", type: "Tứ Quý" },
    { label: "2K", type: "2K" },
    { label: "3K", type: "3K" },
    { label: "4K", type: "4K" },
    { label: "Ù", type: "Ù" },
    { label: "Ù tròn", type: "Ù tròn" },
    { label: "Ù khan", type: "Ù khan" },
    { label: "Nhất", type: "Nhất" },
    { label: "Nhì", type: "Nhì" },
    { label: "Ba", type: "Ba" },
    { label: "Chót", type: "Chót" },
    { label: "Cháy", type: "Cháy" },
  ];